#list methods
print("\nlist methods\n")

pressure = list(map(int, input("Enter pressure values: ").split()))
print("list lenght:",len(pressure),"\n","list value :",pressure)
pressure.append(30)
print("list append: ",pressure)
#pressure.append([30,45])
#print("list append: ",pressure) ***** if i append ([3,4]) it will take it as a whole [3,4] and add as a member single one, and then we cant run the code as no ther element is list like this one
pressure.extend([30,45])
print("list extend: ",pressure)
pressure.remove(30)
print("list remove: ",pressure)
pressure.insert(3,45)
print("list insert: ",pressure)
removed_value = pressure.pop(3)
print("removed value:", removed_value)
print("list pop: ",pressure)
copy_pressure = pressure.copy()
print("list copy: ",copy_pressure)
copy_pressure.clear()
print("list clear: ",copy_pressure)
pressure.sort()
print("list sort: ",pressure)
pressure.reverse()
print("list reverse: ",pressure)
pressure.sort()
print("list sort: ",pressure)
print("list count: ",pressure.count(4))
print("list index: ",pressure.index(4))